server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: wms-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://izzafarisit_db_user:m1s0h4YBhlqSwTUy@cluster0.izvtgwd.mongodb.net/wms_db?retryWrites=true&w=majority&appName=Cluster0}
      auto-index-creation: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# JWT Security Configurations
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expirationMs: ${JWT_EXPIRATION_MS:86400000} # 24 hours
